### ISSUE TITLE
Adding drop down support

### ISSUE THREAD

**Issue by GuidoVries** [liprec/powerbi-hierarchySlicer#36] opened 2018-08-17 12:47 UTC
A great custom visual this is, great also that it is possible to filter the list based on values in measures. Features I'm definatly missing in the standard slicer option. 

However I am missing the drop down support on this visual. Would it be possible to add that in?

Thanks and regards,
Guido

**Comment by liprec** [comment] 2018-08-19 09:39
At this moment it is not possible to implement a drop-down option due to the fact that it is not possible to go outside the sandbox of the custom visual.

_Duplicate of #21, so closing._

**Closed as completed by liprec** 2018-08-19 09:39 UTC
Labels: duplicate
