### ISSUE TITLE
Make parent not clickable

### ISSUE THREAD

**Issue by YUZ-ILO** [liprec/powerbi-hierarchySlicer#109] opened 2019-11-21 16:03 UTC
*Start issue here*
Any way to make the parents just text to group the children but not clickable?

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment] 2019-12-02 14:23
Closing as it is a duplicate of #88.

**Closed as completed by liprec** 2019-12-02 14:23 UTC
