### ISSUE TITLE
A great tool for Power BI

### ISSUE THREAD

**Issue by goldtael** [liprec/powerbi-hierarchySlicer#10] opened 2017-10-14 21:47 UTC
Hierarchy Slicer is great. It is working good in my reports for months but starting last week, for some reasons, the clear, expand all and collapse all functions do not work anymore. Single select in on but the slicer still allows multi-select.

**Comment by liprec** [comment] 2017-10-15 00:38
Fix is coming.

**Comment by liprec** [comment] 2017-10-15 00:38
Duplicate of #9

**Comment by kwarburton** [comment] 2017-10-16 00:16
Look forward to the fix coming through.
Thanks for this great visualisation.

**Comment by liprec** [comment] 2017-10-19 13:10
The latest version of the HierarchySlicer (v1.1.5) is now available for everyone.
Can you confirm that it fixes your issue?

**Comment by goldtael** [comment] 2017-10-20 00:31
Hi Jan:

I just checked it in my reports and this version works flawlessly. I think this slicer is one of the best. Thank you so much.

 

Duc.

**Comment by liprec** [comment] 2017-10-20 00:55
Thanks for the update and enjoy the slicer.

**Closed as completed by liprec** 2017-10-20 00:55 UTC
Labels: bug

**Comment by kwarburton** [comment] 2017-10-20 02:29
Excellent.
Was still not working properly this morning my time (Melbourne) but now work without error.
Must have taken some time for the update to come through.

Thanks so much.

Ken Warburton
Information Management Officer
D: 03 8578 0540 | P: 03 9347 1188 | M: 0409 947 225
ken.warburton@nwmphn.org.au<mailto:ken.warburton@nwmphn.org.au>

**Comment by liprec** [comment] 2017-10-20 02:33
Indeed the CDN network takes some time to populate the new version.
But good to hear that it is working as expected
